### ISSUE TITLE
No permission to push? 

### ISSUE THREAD

**Issue by timbohiatt** [twitivity/twitter-stream.py#12]
Hey Guys, 
trying to help out and make a contribution, not sure if you want it or not. But can't seem to push to your repo even a new branch. Get a permission denied error. Thoughts?

**Comment by saadmanrafat** [comment]
Make sure you have Two Factor Authentication enabled. I'll check The organization settings again. Please do let me know -- if the enabling two-factor authentication works!

**Comment by timbohiatt** [comment]
Can confirm I 100% have two factor enabled on this account.

**Comment by saadmanrafat** [comment]
Thank you for the response! Please wait while I check the settings. Thanks!

**Comment by timbohiatt** [comment]
No problems at all. Happy to wait. Let me know how you go.

**Comment by saadmanrafat** [comment]
@timbohiatt, I think I resolved the issue in an unorthodox manner. Nevertheless, I feel it will work out great. I'm keeping the case open. I can't locate permissions settings. I hope you have received an email.

**Comment by saadmanrafat** [comment]
I hope that solved the issue?

**Comment by saadmanrafat** [comment]
> No problems at all. Happy to wait. Let me know how you go.

Hi again, @timbohiatt 

Github's [ new Interaction Limit ](https://github.blog/2020-12-15-powerful-updates-to-temporary-interaction-limits/) was causing the issue. I've gone over the settings. Please do let me know -- If they are working for you. Sorry for the inconvenience. 

Thanks for your contribution! 

Regards

**Comment by saadmanrafat** [comment]
@timbohiatt  hi there! Were you able to create a pull request? Collaborators are finding it hard to create pull requests from the command line.

**Comment by saadmanrafat** [comment]
@timbohiatt  [Branch Protection Rules](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches)

**Comment by saadmanrafat** [comment]
Default branch protection configurations are changed. Outside collaborators can easily create pull requests! Some protection measures are there to stay. Twitivity will guide how to create PR requests on organizations' repositories @ https://repo.twitivity.dev
